apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-manifest
    repoURL: https://github.com/tanmay6414/argocd-configurations
    targetRevision: master
    directory:
      recurse: true
